---
title: "Week 6 Progress Report"
subtitle: "DATA 450 Capstone"
author: "Nick Nemkov"
date: today
date-format: "[Week ending: ] M/D/YY"
number-sections: false
format:
  pdf: default
---

# Time Log

| Day  | Time  | \# Hours | Task(s) | GH Commit(s) |
|------|-------|----------|---------|--------|
| Mon.  |  |  |  |  |
| Tue.  |  |  |  |  |
| Wed.  |  |  |  |  |
| Thu.  |  |  |  |  |
| Fri.  |  |  |  |  |
| Sat.  |  |  |  |  |
| Sun.  | 12am-2am ; 1pm-6:30pm | 2hrs ; 5.5hrs | Finished Q2 and prepared data for Q3 logistic regression | [Link](https://github.com/NicknNemkov/capstone/commit/2ada7fe788ae4cc4daaff0831eeaa2421ce2a82f)  |

: {tbl-colwidths="[10, 15, 12, 50, 13]"}

**Total \# of hours worked this week: [7.5]**

## What you accomplished (or attempted) this week:

I have finished Question 2 (all visualizations). I have begun working on the machine learning part of my project (Question 3). I currently have one-hot encoded all categorical features, standardized numerical features, and split the data 70/30 into training and testing sets. 

## Any setbacks/roadblocks you experienced:

I created filled bar plots for Question 2, but that didn't show the total count of various races. I then also created a stacked bar plot with the y-axis being the total count of each race. There are now a total of 4 graphs for Question 2.

## What you plan to work on next:

I wish to finish all parts of Question 3 and begin working on Question 4. 

## Are you on track? If not, how will you get back on track?

I am currently on track for my project.
